#Should the discord integration be active?
active = true
#Token of your Discord bot:
bot_token = "ODIwNDAwMDI1MzQ2ODk5OTk5.YE0nEA.9nYeY1VAkPoFyJqz1Qvcs4D-Qgc"
#Channel ID where the bot will be working
#Range: 0 ~ 9223372036854775807
channel_id = 858059446902849556

